# Generated by Django 4.1.2 on 2022-10-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myuser",
            managers=[],
        ),
        migrations.AddField(
            model_name="myuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
